# ======================
#    论坛后端系统配置文件
# ======================

# API服务器所在的端口号
port = 8010

# 数据库连接信息
[database]
url = "mysql://forum:rememberus1nthed%40yofend@10.80.43.196:3306/forum_dev?serverTimezone=Asia/Shanghai"
username = "forum"
password = "rememberus1nthed@yofend"

# Redis连接信息
[redis]
url = "redis://:rememberus@10.80.42.189/13"
# url = "redis://:rememberus@127.0.0.1/13"

# 权限对应用户等级
[permission]
ta = 1
admin = 5
super = 9

# S3文件存储连接信息
[s3]
endpoint = "http://10.80.43.196:9000/"
bucket = "forum"
access_key = "50My98IAnFXDniBxbmFK"
secret_key = "qLfkBObNiIzHOStJzmiSLd6KwTiYnY8qBlOR0T9r"
base_url = "http://10.80.43.196/s3/forum"

[s3.prefix]
upload = "/user-upload/"
avatar = "/user-avatar/"
card_bg = "/user-card/"
homework_upload = "/homework-upload/"

[meili]
host = "http://10.80.42.189:7700"
key = "keI4qhrWElK6UqFt928AkKjDfIn1skn5cXcqP5sLaHo"

[meili.index]
post = "post_dev"
