# ======================
#    论坛后端系统配置文件
# ======================

# 数据库连接信息
[database]
url = "mysql://forum:rememberus1nthed%40yofend@10.80.43.196:3306/forum?serverTimezone=Asia/Shanghai"
username = "forum"
password = "rememberus1nthed@yofend"

# Redis连接信息
[redis]
url = "redis://:rememberus@10.80.42.189/12"

[meili.index]
post = "post"
