# ======================
#    论坛后端系统配置文件
# ======================

# API服务器所在的端口号
port = 8010

# 数据库连接信息
[database]
url = "mysql://forum:rememberus1nthed%40yofend@10.80.43.196:3306/forum_dev"
username = "forum"
password = "rememberus1nthed@yofend"

# Redis连接信息
[redis]
url = "redis://:rememberus@10.80.42.189/13"

# 权限对应用户等级
[permission]
ta = 1
admin = 5
super = 9
