[package]
name = "forum-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
markup5ever = "0.11.0"
once_cell = "1.19.0"
regex = "1.10.3"
scraper = "0.18.1"
